### ISSUE TITLE
error after scanning qr

### ISSUE THREAD

**Issue by Pegorino82** [skyf0l/WhatsAppTerm#14]
Send: new_qrcode_query.--5,["admin", "Conn", "reref"]
Recv: new_qrcode_query.--5,{'status': 200, 'ref': '1@ar7UtapBB7nuuLU9tukBw9mbCo6JjTPtR2MBatVCJaZSqOJU43cXHBO0u/yH2c/VSIniNmvBTg...
...
Recv: s1,['Conn', {'ref': '1@ar7UtapBB7nuuLU9tukBw9mbCo6JjTPtR2MBatVCJaZSqOJU43cXHBO0u/yH2c/VSIniNmvBTg7TSw==...
Send: new_qrcode_query.--6,["admin", "Conn", "reref"]
Recv: s2,['Blocklist', {'id': 1, 'blocklist': []}]
Recv: s3,['Stream', 'update', False, '2.2132.6']
Recv: s4,['Props', {'stickers': 1, 'productCatalogOpenDeeplink': 1, 'productCatalogDeeplink': 1, 'catalogPdpN...
Invalid msg: preempt-77d54327efca0bd8.--2,(data)b'\x05\xaa\xd7\x0b\x80\x9ddw...'
Traceback (most recent call last):
  File "\WhatsAppApi\Client\client_websocket.py", line 58, in __on_message
    msg_data['json'] = self.decrypt_msg(msg_data['data'])
  File "\WhatsAppApi\client.py", line 194, in decrypt_msg
    raise TimeoutError('Generating key timed out')
TimeoutError: Generating key timed out
Please, to fix it, open an issue with this message (hide private data) and briefly explain how it happened
Traceback (most recent call last):
  File "/whatsapp_term.py", line 100, in <module>
    main()
  File "/whatsapp_term.py", line 96, in main
    chat = Chat()
  File "/whatsapp_term.py", line 22, in __init__
    self._client.qrcode_ready_to_scan()
  File "\WhatsAppApi\Client\client_qrcode.py", line 74, in qrcode_ready_to_scan
    self.regen_qrcode()
  File "\WhatsAppApi\Client\client_qrcode.py", line 59, in regen_qrcode
    new_qrcode_result = self.wait_query_pop_json(new_qrcode_query_name)
  File "\WhatsAppApi\client.py", line 184, in wait_query_pop_json
    self.wait_query(query_name)
  File "\WhatsAppApi\client.py", line 177, in wait_query
    raise TimeoutError('Receive message timed out')
TimeoutError: Receive message timed out

**Comment by Pegorino82** [comment]
don't now why, but now it is ok, session was created
